---

- hosts: tag_Project_Safebee
  sudo: yes

  pre_tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Configure Boto
      template: src=templates/etc/boto.cfg
                dest=/etc/boto.cfg

    - name: Create key directory
      file: path=/keys
            state=directory
            owner={{ ansible_ssh_user }}
            group={{ ansible_ssh_user }}
      tags:
        - deploy

    - name: Deploy deploy key
      copy: src=files/keys/phoenix_deploy
            dest={{ django_deploy_key }}
            owner={{ ansible_ssh_user }}
            group={{ ansible_ssh_user }}
            mode=0600
      tags:
        - deploy

    - name: Install system requirements
      apt: name={{ item }}
           update_cache=yes
      with_items:
        - build-essential
        - emacs
        - git
        - libxml2-dev
        - libxslt1-dev
        - python-boto
        - python-dev
        - python-pip

  roles:
    - role: geerlingguy.ntp
      ntp_timezone: America/New_York

- hosts: vagrant
  vars:
    db_dump: Safebee.dump

  pre_tasks:
    - name: Install vagrant requirements
      apt: name={{ item }}
      sudo: yes
      with_items:
        - memcached

    - stat: path=/var/www/loop
      register: mnn_src

    - stat: path=/vagrant/{{ db_dump }}
      register: djangodb_st

    - name: Get Prod DB copy
      s3: bucket=tech-only.mnn.com
          object=/DB_Dumps/{{ db_dump }}
          dest=/vagrant/{{ db_dump }}
          mode=get
          aws_access_key={{ aws_access_key }}
          aws_secret_key={{ aws_secret_key }}
      when: djangodb_st.stat.exists == false

    - name: Fix permissions
      file: path=/var/www/loop
            state=directory
            group={{ ansible_ssh_user }}
            owner={{ ansible_ssh_user }}
      sudo: yes
      when: mnn_src.stat.exists == false

  roles:
    - role: mnn.postgresql
      sudo: yes
      postgresql_database: safebee_db
      postgresql_user: safebee
      postgresql_password: changeme
      postgresql_dump: /vagrant/{{ db_dump }}

- hosts: tag_Layer_Admin
  sudo: yes

  pre_tasks:
    - name: Install Memcached
      apt: name=memcached

  roles:
    - role: mnn.nginx
      tags:
        - deploy
    - role: gcporras.virtualenvwrapper
    - role: mnn.django
      tags:
        - deploy
    - role: mnn.supervisor
      tags:
        - deploy

  post_tasks:
    - name: Add project path link to virtualenvwrapper dir
      template: src=templates/virtualenvwrapper.project
                owner={{ ansible_ssh_user }}
                group={{ ansible_ssh_user }}
                dest="{{ django_project_path }}/.project"

- hosts: tag_Layer_Webapp
  sudo: yes

  roles:
    - role: mnn.nginx
      tags:
        - deploy
    - role: mnn.nginx-pagespeed
    - role: gcporras.virtualenvwrapper
    - role: mnn.django
      tags:
        - deploy

  post_tasks:
    - name: Add project path link to virtualenvwrapper dir
      template: src=templates/virtualenvwrapper.project
                owner={{ ansible_ssh_user }}
                group={{ ansible_ssh_user }}
                dest="{{ django_project_path }}/.project"
